[project]
name = "fbpyutils"
version = "1.5.4"
description = "Francisco Bispo's Utilities for Python"
readme = "README.md"
requires-python = ">=3.11,<4.0"
license = { text = "Apache-2.0" }
authors = [
    { name = "Francisco C J Bispo", email = "fcjbispo@franciscobispo.net" },
]
dependencies = [
    "pandas==2.2.2",
    "ofxparse>=0.21,<0.22",
    "pytz>=2024.1,<2025.0",
    "python-magic==0.4.13",
    "python-magic-win64>=0.4.13,<0.5.0",
    "openpyxl>=3.1.5,<4.0.0",
    "xlrd>=2.0.1,<3.0.0",
    "sqlalchemy==2.0.32",
    "google-api-python-client>=2.143.0,<3.0.0",
    "google-auth-httplib2>=0.2.0,<0.3.0",
    "google-auth-oauthlib>=1.2.1,<2.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "requests==2.32.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "vistir==0.6.1",
    "ipykernel>=6.29.5,<7.0.0",
    "ipython>=8.27.0,<9.0.0",
    "jupytex>=0.0.3,<0.0.4",
    "black>=24.8.0,<25.0.0",
    "autopep8>=2.3.1,<3.0.0",
    "pytest>=8.3.2,<9.0.0",
    "pytest-mock>=3.14.0,<4.0.0",
]

