[tool.poetry]
name = "fbpyutils"
version = "1.5.3"
description = "Francisco Bispo's Utilities for Python"
authors = ["Francisco C J Bispo <fcjbispo@fcjbispo.net>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "2.2.2"
ofxparse = "^0.21"
pytz = "^2024.1"
python-magic = "0.4.13"
python-magic-win64 = "^0.4.13"
openpyxl = "^3.1.5"
xlrd = "^2.0.1"
sqlalchemy = "2.0.32"
google-api-python-client = "^2.143.0"
google-auth-httplib2 = "^0.2.0"
google-auth-oauthlib = "^1.2.1"
python-dotenv = "^1.0.1"
requests = "2.32.3"

[tool.poetry.group.dev.dependencies]
vistir = "0.6.1"
ipykernel = "^6.29.5"
ipython = "^8.27.0"
jupytex = "^0.0.3"
black = "^24.8.0"
autopep8 = "^2.3.1"
pytest = "^8.3.2"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"